version: 2.1
orbs:
  tweeter-orb: jollof-guy/tweeter-orb@0.2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
      - image: cimg/postgres:14.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_name

    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run:
          name: install dockerize # This is a utility that will attempt to connect to a database, in place of an application for this sample.
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db # If no database is found in 1 minute the job will fail.
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

workflows:
  build-workflow:
    jobs:
      - build
      - tweeter-orb/tweet:
            tweet: "Hello World"
            key: "KRQsNdPI2JN9Ebc96AMWSCKls"
            secret: "rLOoZJDJszB0g6Jml09347v0pO8KrUGojt0DoMd5Y8ZgqHw9OQ"