version: 2.1

parameters:
  condition-workflow:
    type: boolean
    default: true

jobs:
  my-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - when:
          condition:
            # Add condition to execute this step when the github branch is equal to 'main'
            and:
            - equal: [Exercise-14, << pipeline.git.branch >>]
          steps:
            - run: echo "I am on Exercise-14"

  conditional-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run: echo "This ran on a pipeline parameter"

workflows:
  my-workflow:
    jobs:
      - my-job

  conditional-workflow:
    when:
      and:
        - equal: [true, << pipeline.parameters.condition-workflow >>]
        # Add condition to execute this workflow when condition-workflow is equal to true
    jobs:
      - conditional-job