version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout
      # Uncomment below and set the key to point to the proper file
      - run: cd '06 Caching'; ls
      - restore_cache:
          name: Restore Yarn Package Json Cache
          keys:   
            - yarn-packages-{{ checksum "package.json" }}         
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run: ls
      # Uncomment below and set the key to point to the proper file
      - save_cache:
          name: Save Yarn Package Json Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: ls

workflows:
  cache-save-and-restore:
    jobs:
      - build