version: 2.1

orbs:
  win: circleci/windows@2.2.0 

jobs:
  build-docker:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "docker image"
  build-arm-machine:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
  build-windows:
    executor: win/server-2022
    steps:
      - checkout
  build-mac:
    macos:
      xcode: 13.4.0
    steps:
      - checkout



workflows:
  build:
    jobs:
      - build-docker
      - build-arm-machine
      - build-mac
      - build-windows

